# Generated by Django 4.2.5 on 2023-09-07 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('INFRAESTRUCTURA', 'INFRAESTRUCTURA'), ('CURRÍCULO', 'CURRÍCULO'), ('FORMACIÓN / INSTRUCCIÓN / EVALUACIÓN', 'FORMACIÓN / INSTRUCCIÓN / EVALUACIÓN'), ('PERSONAL DOCENTE Y ADMINISTRATIVO', 'PERSONAL DOCENTE Y ADMINISTRATIVO'), ('ESCUELA, COMUNIDAD Y PERTENENCIA', 'ESCUELA, COMUNIDAD Y PERTENENCIA')], default='INFRAESTRUCTURA', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonResponsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Ingrese primer nombre', max_length=100)),
                ('last_name', models.CharField(help_text='Ingrese primer apellido', max_length=100)),
                ('phone_number', models.CharField(help_text='+XX XXX XX XX', max_length=15)),
                ('email', models.EmailField(default='example@example.com', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Equidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeral', models.CharField(choices=[('Todos los estudiantes reciben acceso equitativo a la formación y a los programas. No se selecciona únicamente a los estudiantes con gusto por las asignaturas S.T.E.M., todos los estudiantes hacen parte del programa', '1'), ('Todos los estudiantes con necesidades específicas e identificadas están siendo ubicados para facilitar su adaptación. Aprendizaje individualizado.', '2'), ('Se han diseñado acciones o planes especiales para alentar a los estudiantes con bajo interés o desempeño a desarrollar interés en las carreras STEM.', '3'), ('Los docentes reciben desarrollo profesional sobre las diferencias culturales y de género para enriquecer la formación.', '4'), ('El aula STEM se diferencia en ubicar a todos los estudiantes, con una consideración especial hacia todos los grupos geográficos, socioeconómicos, raciales, étnicos y de género.', '5'), ('La institución está preparada para proveer una formación incluyente. Promueve las oportunidades de aprendizaje para todos los estudiantes, pero respeta las diferencias culturales y de género.', '6')], max_length=1000)),
                ('sub_numeral', models.CharField(choices=[('Procesos claros desarrollados para la inducción de nuevos estudiantes.', '1'), ('Programa o actividades que garanticen una transición efectiva para los estudiantes.', '2'), ('La educación STEM es incluyente, y una forma importante es hacer que se sientan como en casa a través de actividades o de programas, con suficiente anterioridad para que puedan participar en la labor académica, no como extraños sino ya apropiados de las costumbres de los estudiantes veteranos.', '3'), ('La institución tiene por objetivo incrementar la participación de la mujer en las áreas STEM, de tal manera que la población estudiantil involucrada en el programa sea cada vez mayor. ', '4')], max_length=500)),
                ('priority_model', models.CharField(choices=[(' ', 'Exploratorio'), (' ', 'Introductorio'), ('', 'Inmerción parcial'), (' ', 'Inmerción completa')], default='Introductorio', max_length=4)),
                ('dep_responsable', models.CharField(default='Dirección', max_length=30)),
                ('track_year', models.IntegerField(help_text='Ingrese año de seguimiento')),
                ('track_date', models.CharField(help_text='Ingrese fecha de seguimiento', max_length=5)),
                ('internal_auditory_date', models.DateField(default='31/01/2000', null=True)),
                ('internal_auditory_obs', models.TextField(blank=True, max_length=1000)),
                ('external_auditory_date', models.DateField(blank=True, default='31/01/2000', null=True)),
                ('external_auditory_obs', models.TextField(blank=True, max_length=1000)),
                ('criterio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DataBase.criterio')),
                ('person_responsable', models.ManyToManyField(help_text='Seleccione un responsable', to='DataBase.personresponsable')),
            ],
        ),
        migrations.CreateModel(
            name='AprendizajeCentrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_model', models.CharField(choices=[(' ', 'Exploratorio'), (' ', 'Introductorio'), ('', 'Inmerción parcial'), (' ', 'Inmerción completa')], default='Introductorio', max_length=4)),
                ('dep_responsable', models.CharField(default='Dirección', max_length=30)),
                ('track_year', models.IntegerField(help_text='Ingrese año de seguimiento')),
                ('track_date', models.CharField(help_text='Ingrese fecha de seguimiento', max_length=5)),
                ('internal_auditory_date', models.DateField(default='31/01/2000', null=True)),
                ('internal_auditory_obs', models.TextField(blank=True, max_length=1000)),
                ('external_auditory_date', models.DateField(blank=True, default='31/01/2000', null=True)),
                ('external_auditory_obs', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numeral', models.CharField(choices=[('Formación/Instrucción basada en Aprendizaje Basado en Lecciones / Aprendizaje Basado en Proyectos / Aprendizaje enfocado en la indagación.', '1'), ('El aprendizaje es centrado en el estudiante. La dinámica de aula y en general en la institución se prevé el tiempo para investigación y trabajo en equipo, así como de tiempo de consulta a los profesores en tiempo fuera del horario de la asignatura.', '2'), ('Los proyectos son centrales al currículo. Los objetivos de los proyectos serán la meta más importante para lograr aprobar el grado escolar.', '3'), ('Dentro de las experiencias de aula predominarán los retos de ingeniería como parte del ABP-ABL.', '4')], max_length=10000)),
                ('criterio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DataBase.criterio')),
                ('person_responsable', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DataBase.personresponsable')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
