# Generated by Django 4.2.5 on 2023-09-05 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PersonResponsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Equidad',
            fields=[
                ('numeral', models.CharField(choices=[(1, 'Todos los estudiantes reciben acceso equitativo a la formación y a los programas. No se selecciona únicamente a los estudiantes con gusto por las asignaturas S.T.E.M., todos los estudiantes hacen parte del programa'), (2, 'Todos los estudiantes con necesidades específicas e identificadas están siendo ubicados para facilitar su adaptación. Aprendizaje individualizado.'), (3, 'Se han diseñado acciones o planes especiales para alentar a los estudiantes con bajo interés o desempeño a desarrollar interés en las carreras STEM.'), (4, 'Los docentes reciben desarrollo profesional sobre las diferencias culturales y de género para enriquecer la formación.'), (5, 'El aula STEM se diferencia en ubicar a todos los estudiantes, con una consideración especial hacia todos los grupos geográficos, socioeconómicos, raciales, étnicos y de género.'), (6, 'La institución está preparada para proveer una formación incluyente. Promueve las oportunidades de aprendizaje para todos los estudiantes, pero respeta las diferencias culturales y de género.')], max_length=6, primary_key=True, serialize=False)),
                ('priority_model', models.CharField(choices=[(1, 'Exploratorio'), (2, 'Introductorio'), (3, 'Inmerción parcial'), (4, 'Inmerción completa')], default='Introductorio', max_length=4)),
                ('dep_responsable', models.CharField(default='Dirección', max_length=30)),
                ('track_year', models.IntegerField(help_text='Ingrese año de seguimiento')),
                ('track_date', models.CharField(help_text='Ingrese fecha de seguimiento', max_length=5)),
                ('auditory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DataBase.auditory')),
                ('person_responsable', models.ManyToManyField(help_text='Seleccione un responsable', to='DataBase.personresponsable')),
            ],
        ),
    ]
