# Generated by Django 4.2.2 on 2023-09-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equidad',
            name='priority_model',
            field=models.CharField(choices=[(' ', 'Exploratorio'), (' ', 'Introductorio'), ('', 'Inmerción parcial'), (' ', 'Inmerción completa')], default='Introductorio', max_length=4),
        ),
        migrations.AlterField(
            model_name='equidad',
            name='internal_auditory_date',
            field=models.DateField(default='31/01/2000', null=True),
        ),
        migrations.RemoveField(
            model_name='equidad',
            name='person_responsable',
        ),
        migrations.AddField(
            model_name='equidad',
            name='person_responsable',
            field=models.ManyToManyField(help_text='Seleccione un responsable', to='DataBase.personresponsable'),
        ),
    ]
