# Generated by Django 4.2.5 on 2023-09-13 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcreteInclusionIngenieriaAula',
            fields=[
                ('inclusion_ingenieria_aula_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='DataBase.inclusion_ingenieria_aula')),
            ],
            options={
                'abstract': False,
            },
            bases=('DataBase.inclusion_ingenieria_aula',),
        ),
    ]
