# Generated by Django 4.2.5 on 2023-09-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterio',
            name='name',
            field=models.CharField(choices=[('1000', 'INFRAESTRUCTURA'), ('2000', 'CURRÍCULO'), ('3000', 'FORMACIÓN / INSTRUCCIÓN / EVALUACIÓN'), ('4000', 'PERSONAL DOCENTE Y ADMINISTRATIVO'), ('5000', 'ESCUELA, COMUNIDAD Y PERTENENCIA')], default='INFRAESTRUCTURA', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='model',
            field=models.CharField(choices=[('Exploratorio', 'Exploratorio'), ('Introductorio', 'Introductorio'), ('Inmersión parcial', 'Inmersión parcial'), ('Inmersión completa', 'Inmersión completa')], max_length=18),
        ),
    ]
