# Generated by Django 4.2.5 on 2023-09-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprendizajecentrado',
            name='subnumeral',
            field=models.CharField(blank=True, choices=[('3.1.2.1', 'Autonomía del estudiante'), ('3.1.2.2', 'Los estudiantes descubren qué lo que están aprendiendo es importante para su vida y su comunidad.'), ('3.1.2.3', 'Los estudiantes le dan importancia y relevancia a las actividades que se hacen durante sus clases. Toman control sobre el desarrollo del aprendizaje.'), ('3.1.2.4', 'Los estudiantes demuestran su conocimiento sobre las áreas STEM y que son base de una formación en educación STEM')], max_length=250),
        ),
    ]
