# Generated by Django 4.2.5 on 2023-09-15 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aprendizajecentrado',
            name='evidence',
            field=models.URLField(blank=True, help_text='Ingrese sus evidencias aquí'),
        ),
        migrations.AddField(
            model_name='compromisodelacomunidad',
            name='evidence',
            field=models.URLField(blank=True, help_text='Ingrese sus evidencias aquí'),
        ),
        migrations.AddField(
            model_name='convivenciaescolar',
            name='evidence',
            field=models.URLField(blank=True, help_text='Ingrese sus evidencias aquí'),
        ),
        migrations.AddField(
            model_name='curriculoprogresivo',
            name='evidence',
            field=models.URLField(blank=True, help_text='Ingrese sus evidencias aquí'),
        ),
        migrations.AddField(
            model_name='curriculopropio',
            name='evidence',
            field=models.URLField(blank=True, help_text='Ingrese sus evidencias aquí'),
        ),
        migrations.AddField(
            model_name='desarrollociudadaniadigital',
            name='evidence',
            field=models.URLField(blank=True, help_text='Ingrese sus evidencias aquí'),
        ),
        migrations.AddField(
            model_name='educacionstemintegrada',
            name='evidence',
            field=models.URLField(blank=True, help_text='Ingrese sus evidencias aquí'),
        ),
        migrations.AddField(
            model_name='equidad',
            name='evidence',
            field=models.URLField(blank=True, help_text='Ingrese sus evidencias aquí'),
        ),
        migrations.AddField(
            model_name='evaluacionestudiantes',
            name='evidence',
            field=models.URLField(blank=True, help_text='Ingrese sus evidencias aquí'),
        ),
        migrations.AddField(
            model_name='inclusioningenieriaaula',
            name='evidence',
            field=models.URLField(blank=True, help_text='Ingrese sus evidencias aquí'),
        ),
        migrations.AddField(
            model_name='relacionesconlacominudad',
            name='evidence',
            field=models.URLField(blank=True, help_text='Ingrese sus evidencias aquí'),
        ),
        migrations.AddField(
            model_name='sostenibilidadescuelacomunidadypertenencia',
            name='evidence',
            field=models.URLField(blank=True, help_text='Ingrese sus evidencias aquí'),
        ),
    ]
