# Generated by Django 4.2.5 on 2023-09-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprendizajecentrado',
            name='numeral',
            field=models.CharField(choices=[('Formación/Instrucción basada en Aprendizaje Basado en Lecciones / Aprendizaje Basado en Proyectos / Aprendizaje enfocado en la indagación.', '3.1.1'), ('El aprendizaje es centrado en el estudiante. La dinámica de aula y en general en la institución se prevé el tiempo para investigación y trabajo en equipo, así como de tiempo de consulta a los profesores en tiempo fuera del horario de la asignatura.', '3.1.2'), ('Los proyectos son centrales al currículo. Los objetivos de los proyectos serán la meta más importante para lograr aprobar el grado escolar.', '3.1.3'), ('Dentro de las experiencias de aula predominarán los retos de ingeniería como parte del ABP-ABL.', '3.1.4')], max_length=10000),
        ),
    ]
