# Generated by Django 4.2.5 on 2023-09-15 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducacionStemIntegrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(help_text='Ingrese el nivel de prioridad del 1 al 10 para el numeral', null=True)),
                ('dep_responsable', models.CharField(default='Dirección', max_length=30)),
                ('track_year', models.IntegerField(help_text='Ingrese año de seguimiento')),
                ('track_date', models.CharField(help_text='Ingrese fecha de seguimiento', max_length=5)),
                ('internal_auditory_date', models.DateField(blank=True, default='31/01/2000', null=True)),
                ('internal_auditory_obs', models.TextField(blank=True, max_length=1000)),
                ('external_auditory_date', models.DateField(blank=True, default='31/01/2000', null=True)),
                ('external_auditory_obs', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numeral', models.CharField(choices=[('3.4.1', 'Todos los profesores integran diseño en ingeniería, aplicaciones tecnológicas, investigación y análisis matemático. Evidencia de educación STEM integrada en todas las aulas.'), ('3.4.2', 'Los contenidos de las actividades han sido diseña con base en una propuesta de currículo que incluye problemas del mundo real y de situaciones que le son relevantes a los estudiantes.'), ('3.4.3', 'Las actividades se deseñan con una pedagogía centrada en el estudiante'), ('3.4.4', 'Las actividades se desarrollan enfocadas al trabajo en equipo y la colaboración entre los estudiantes'), ('3.4.5', 'Las actividades se diseñan con una base fundamental de ciencias y matemáticas e incluyendo en lo posibles otras áreas del currículo.')], max_length=250)),
                ('sub_numeral_1', models.CharField(choices=[('3.4.1.1', 'Retos de ingeniería incluidos en las actividades.'), ('3.4.1.2', 'Los estudiantes aprenden de las fallas o fracasos en el diseño, tienen la oportunidad de rediseñar y consideran "fallar" como parte cotidiana en el proceso de diseño.')], max_length=180)),
                ('sub_numeral_2', models.CharField(choices=[('3.4.2.1', 'Los contextos de las actividades y proyectos involucran a los estudiantes dada la relevancia de éstos.'), ('3.4.2.2', 'La selección de temas considera los intereses de los estudiantes, así como aquellos asuntos de mayor relevancia para la comunidad.')], max_length=150)),
                ('criterio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DataBase.criterio')),
                ('person_responsable', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DataBase.personresponsable')),
            ],
            options={
                'verbose_name': 'Educación STEM integrada',
                'verbose_name_plural': 'Educación STEM integrada',
            },
        ),
    ]
