# Generated by Django 4.2.5 on 2023-09-05 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('name', models.CharField(choices=[(1, 'INFRAESTRUCTURA'), (2, 'CURRÍCULO'), (3, 'FORMACIÓN / INSTRUCCIÓN / EVALUACIÓN'), (4, 'PERSONAL DOCENTE Y ADMINISTRATIVO'), (5, 'ESCUELA, COMUNIDAD Y PERTENENCIA')], max_length=5, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameField(
            model_name='equidad',
            old_name='numeral',
            new_name='item',
        ),
        migrations.AddField(
            model_name='equidad',
            name='criterio',
            field=models.ForeignKey(default='INFRAESTRUCTURA', null=True, on_delete=django.db.models.deletion.SET_NULL, to='DataBase.criterio'),
        ),
    ]
