# Generated by Django 4.2.5 on 2023-09-20 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculoprogresivo',
            name='codigo',
            field=models.CharField(default='3000', max_length=7),
        ),
        migrations.AddField(
            model_name='curriculopropio',
            name='codigo',
            field=models.CharField(default='3000', max_length=7),
        ),
        migrations.AddField(
            model_name='desarrollociudadaniadigital',
            name='codigo',
            field=models.CharField(default='3000', max_length=7),
        ),
        migrations.AddField(
            model_name='evaluacionestudiantes',
            name='codigo',
            field=models.CharField(default='3000', max_length=7),
        ),
        migrations.AddField(
            model_name='inclusioningenieriaaula',
            name='codigo',
            field=models.CharField(default='3000', max_length=7),
        ),
        migrations.AlterField(
            model_name='curriculoprogresivo',
            name='numeral',
            field=models.CharField(choices=[('2500', '2500 - CURRÍCULO PROGRESIVO Y ALINEADO CON LOS ESTÁNDARES CURRICULARES'), ('2510', '2510 - Los equipos de profesores planean verticalmente la instrucción STEM dentro de la institución educativa.'), ('2520', '2520 - El currículo está alineado con los estándares académicos actuales.'), ('2530', '2530 - Las conexiones con las carreras relacionadas con las áreas STEM son una parte regular del currículo.'), ('2540', '2540 - Se incluyen buenas prácticas de estándares internacionales que complementan y apoyan los estándares locales obligatorios.')], max_length=10000),
        ),
        migrations.AlterField(
            model_name='curriculopropio',
            name='numeral',
            field=models.CharField(choices=[('2600', '2600 - CURRÍCULO PROPIO'), ('261', '261 - El currículo es desarrollado por docentes o personas especializadas de la institución educativa, esto incluye la creación de actividades y proyectos.'), ('262', '262 - El mejor aporte para un currículo en educación STEM será siempre aquel contenido creado por los propios profesores. Los profesores conocen sus estudiantes y saben qué temas y que aspectos les son interesantes y por eso pueden crear actividades y proyectos especiales para sus estudiantes.')], max_length=10000),
        ),
        migrations.AlterField(
            model_name='desarrollociudadaniadigital',
            name='numeral',
            field=models.CharField(choices=[('2300', '2300 - DESARROLLO DE UNA CIUDADANÍA DIGITAL'), ('231', '231 - Establecimiento de una alfabetización digital como parte del entendimiento y el alcance de los desarrollos dentro de la 4a revolución industrial.'), ('232', '232 - Integración del mundo real al mundo virtual y su relación con la vida personal y laboral.'), ('233', '233 - Integración constante de nuevos desarrollos digitales dentro de actividades curriculares.'), ('234', '234 - Desarrollo de hábitos de aprendizaje continuo sobre nuevas alternativas y soluciones que aparecen dentro del mundo digital con miras al conocimiento crítico como consumidor y productor digital.')], max_length=10000),
        ),
        migrations.AlterField(
            model_name='evaluacionestudiantes',
            name='numeral',
            field=models.CharField(choices=[('2800', '2800 - EVALUACIÓN DE LOS ESTUDIANTES'), ('2810', '2810 - El currículo incluye actividades para que los docentes usen evaluaciones basadas en el desempeño para determinar el aprendizaje de los estudiantes.'), ('2820', '2820 - Las evaluaciones previas / posteriores se utilizan para mostrar el desarrollo académico de los estudiantes.'), ('2830', '2830 - Se diseñan las actividades para que los profesores observen y monitoreen el diálogo entre los estudiantes para evaluar los procesos en la resolución de problemas y la innovación.'), ('2840', '2840 - Se diseñan las actividades para que los estudiantes participen en la autoevaluación y el establecimiento de metas.'), ('2850', '2850 - La institución utiliza datos de evaluaciones estatales y escolares para impulsar las decisiones de la formación.'), ('2860', '2860 - Evaluación continua. Tipología de evaluación donde los alumnos son examinados continuamente.'), ('2870', '2870 - Asesoramiento personalizado. Tipología de evaluación enmarcada para demostrar si los alumnos han alcanzado objetivos educativos específicos, de acuerdo con su desarrollo personal.')], max_length=10000),
        ),
        migrations.AlterField(
            model_name='inclusioningenieriaaula',
            name='numeral',
            field=models.CharField(choices=[('2200', '2200 - INCLUSIÓN DE LA INGENIERÍA EN EL AULA'), ('2210', '2210 - Inclusión del proceso de diseño en ingeniería en el currículo.'), ('2220', '2220 - Los docentes de la mayoría de las asignaturas adoptan el proceso de diseño como parte fundamental del desarrollo pedagógico.'), ('2230', '2230 - El proceso de diseño se ejecuta de forma intencional dado el potencial pedagógico de cada una de sus fases.'), ('2240', '2240 - Las actividades se diseñan con el objetivo de incluir el pensamiento computacional y el pensamiento matemático en la gran mayoría de las asignaturas.'), ('2250', '2250 - Actividades de prototipado en espacios para la creatividad (Maker Spaces)')], max_length=10000),
        ),
    ]
