# Generated by Django 4.2.5 on 2023-09-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0002_criterio_rename_numeral_equidad_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterio',
            name='name',
            field=models.CharField(choices=[(1, 'INFRAESTRUCTURA'), (2, 'CURRÍCULO'), (3, 'FORMACIÓN / INSTRUCCIÓN / EVALUACIÓN'), (4, 'PERSONAL DOCENTE Y ADMINISTRATIVO'), (5, 'ESCUELA, COMUNIDAD Y PERTENENCIA')], max_length=100, primary_key=True, serialize=False),
        ),
    ]
