# Generated by Django 4.2.5 on 2023-09-15 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0002_aprendizajecentrado_evidence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TecnologiaFormacionInstruccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(help_text='Ingrese el nivel de prioridad del 1 al 10 para el numeral', null=True)),
                ('dep_responsable', models.CharField(default='Dirección', max_length=30)),
                ('track_year', models.IntegerField(help_text='Ingrese año de seguimiento')),
                ('track_date', models.CharField(help_text='Ingrese fecha de seguimiento', max_length=5)),
                ('internal_auditory_date', models.DateField(blank=True, default='31/01/2000', null=True)),
                ('internal_auditory_obs', models.TextField(blank=True, max_length=1000)),
                ('external_auditory_date', models.DateField(blank=True, default='31/01/2000', null=True)),
                ('external_auditory_obs', models.TextField(blank=True, max_length=1000)),
                ('evidence', models.URLField(blank=True, help_text='Ingrese sus evidencias aquí')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numeral', models.CharField(choices=[('Los docentes utilizan elementos tecnológicos que apoyan la docencia de forma diaria.', '3510'), ('Los profesores requieren que los estudiantes usen la tecnología apropiada y disponible para el trabajo de colaboración, comunicación, investigación,  recopilación y análisis de datos, en proyectos y otras evaluaciones diarias', '3520'), ('Herramientas computacionales y tecnologías virtuales están integradas al Programa en Educación STEM.', '3530')], max_length=250)),
                ('person_responsable', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DataBase.personresponsable')),
            ],
            options={
                'verbose_name': 'Tecnología para la formacion / instrucción',
                'verbose_name_plural': 'Tecnología para la formacion / instrucción',
            },
        ),
    ]
