# Generated by Django 4.2.5 on 2023-09-08 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0002_alter_equidad_sub_numeral_relacionesconlacominudad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprendizajecentrado',
            name='internal_auditory_date',
            field=models.DateField(blank=True, default='31/01/2000', null=True),
        ),
        migrations.AlterField(
            model_name='compromisodelacominudad',
            name='internal_auditory_date',
            field=models.DateField(blank=True, default='31/01/2000', null=True),
        ),
        migrations.AlterField(
            model_name='compromisodelacominudad',
            name='numeral',
            field=models.CharField(choices=[('511', 'Los miembros de la comunidad son socios en el liderazgo del Programa en Educación STEM, evaluación de necesidades y guía de ayuda para la institución.'), ('512', 'El programa ha incluido a diversos socios para guiar el trabajo en la institución.'), ('513', 'Existen oportunidades para presentar el trabajo de los estudiantes a través de eventos comunitarios a través de exposiciones en el sitio o en línea.'), ('514', 'La institución recopila y utiliza los comentarios de los padres / la comunidad para evaluar el progreso de la implementación del Programa en Educación STEM.'), ('515', 'La escuela proporciona oportunidades de sensibilización comunitaria para los padres. Hay comunicación permanente a los padres de familia.')], max_length=10000),
        ),
        migrations.AlterField(
            model_name='relacionesconlacominudad',
            name='internal_auditory_date',
            field=models.DateField(blank=True, default='31/01/2000', null=True),
        ),
        migrations.AlterField(
            model_name='relacionesconlacominudad',
            name='numeral',
            field=models.CharField(choices=[('521', 'Los estudiantes tienen experiencias directas con profesionales de áreas STEM en entornos auténticos.'), ('522', 'Las experiencias de campo y con profesionales invitados están integrados dentro de las actividades para aumentar el conocimiento de los estudiantes y ayudar en la selección de carrera.')], max_length=10000),
        ),
        migrations.CreateModel(
            name='Sostenibilidad_EscuelaComunidadyPertenencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_model', models.CharField(choices=[(' ', 'Exploratorio'), (' ', 'Introductorio'), ('', 'Inmerción parcial'), (' ', 'Inmerción completa')], default='Introductorio', max_length=4)),
                ('dep_responsable', models.CharField(default='Dirección', max_length=30)),
                ('track_year', models.IntegerField(help_text='Ingrese año de seguimiento')),
                ('track_date', models.CharField(help_text='Ingrese fecha de seguimiento', max_length=5)),
                ('internal_auditory_date', models.DateField(blank=True, default='31/01/2000', null=True)),
                ('internal_auditory_obs', models.TextField(blank=True, max_length=1000)),
                ('external_auditory_date', models.DateField(blank=True, default='31/01/2000', null=True)),
                ('external_auditory_obs', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numeral', models.CharField(choices=[('541', 'Se mantienen relaciones de cooperación de la empresa privada, entidades educativas y universidades para lograr las experiencias profesionales que requieren los estudiantes en su proceso de selección de carrera.'), ('542', 'Se establecen nuevas relaciones con la comunidad y se mantienen las antiguas para garantizar el liderazgo de la comunidad en el Programa en Educación STEM.')], max_length=10000)),
                ('criterio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DataBase.criterio')),
                ('person_responsable', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DataBase.personresponsable')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConvivenciaEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_model', models.CharField(choices=[(' ', 'Exploratorio'), (' ', 'Introductorio'), ('', 'Inmerción parcial'), (' ', 'Inmerción completa')], default='Introductorio', max_length=4)),
                ('dep_responsable', models.CharField(default='Dirección', max_length=30)),
                ('track_year', models.IntegerField(help_text='Ingrese año de seguimiento')),
                ('track_date', models.CharField(help_text='Ingrese fecha de seguimiento', max_length=5)),
                ('internal_auditory_date', models.DateField(blank=True, default='31/01/2000', null=True)),
                ('internal_auditory_obs', models.TextField(blank=True, max_length=1000)),
                ('external_auditory_date', models.DateField(blank=True, default='31/01/2000', null=True)),
                ('external_auditory_obs', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numeral', models.CharField(choices=[('531', 'Los estudiantes se tratan con confianza y respeto.'), ('532', 'El docente facilita un ambiente positivo de aprendizaje social y emocional.'), ('533', 'El personal del colegio enfatiza en el código de conducta y los valores.'), ('534', 'El personal de la institución apoya las necesidades de todos los estudiantes.'), ('535', 'Los estudiantes contribuyen en las decisiones de la institución.'), ('536', 'Los estudiantes demuestran la aplicación del código de conducta y los valores.')], max_length=10000)),
                ('criterio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DataBase.criterio')),
                ('person_responsable', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DataBase.personresponsable')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
