# Generated by Django 4.2.5 on 2023-09-13 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0002_concreteinclusioningenieriaaula'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConcreteInclusionIngenieriaAula',
        ),
    ]
