# Generated by Django 4.2.5 on 2023-09-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0002_alter_aprendizajecentrado_subnumeral'),
    ]

    operations = [
        migrations.AddField(
            model_name='compromisodelacomunidad',
            name='codigo',
            field=models.CharField(default='500', max_length=3),
        ),
        migrations.AlterField(
            model_name='compromisodelacomunidad',
            name='numeral',
            field=models.CharField(choices=[('Los miembros de la comunidad son socios en el liderazgo del Programa en Educación STEM, evaluación de necesidades y guía de ayuda para la institución.', '511'), ('El programa ha incluido a diversos socios para guiar el trabajo en la institución.', '512'), ('Existen oportunidades para presentar el trabajo de los estudiantes a través de eventos comunitarios a través de exposiciones en el sitio o en línea.', '513'), ('La institución recopila y utiliza los comentarios de los padres / la comunidad para evaluar el progreso de la implementación del Programa en Educación STEM.', '514'), ('La escuela proporciona oportunidades de sensibilización comunitaria para los padres. Hay comunicación permanente a los padres de familia.', '515')], max_length=10000),
        ),
    ]
