# Generated by Django 4.2.5 on 2023-09-16 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0003_tecnologiaformacioninstruccion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TecnologiaFormacionInstruccion',
            new_name='TecnologiaFormacion',
        ),
    ]
