# Generated by Django 4.2.5 on 2023-09-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0003_alter_criterio_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterio',
            name='name',
            field=models.CharField(choices=[(1, 'INFRAESTRUCTURA'), (2, 'CURRÍCULO'), (3, 'FORMACIÓN / INSTRUCCIÓN / EVALUACIÓN'), (4, 'PERSONAL DOCENTE Y ADMINISTRATIVO'), (5, 'ESCUELA, COMUNIDAD Y PERTENENCIA')], default='INFRAESTRUCTURA', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='equidad',
            name='criterio',
        ),
        migrations.AlterField(
            model_name='equidad',
            name='item',
            field=models.CharField(choices=[(1, 'Todos los estudiantes reciben acceso equitativo a la formación y a los programas. No se selecciona únicamente a los estudiantes con gusto por las asignaturas S.T.E.M., todos los estudiantes hacen parte del programa'), (2, 'Todos los estudiantes con necesidades específicas e identificadas están siendo ubicados para facilitar su adaptación. Aprendizaje individualizado.'), (3, 'Se han diseñado acciones o planes especiales para alentar a los estudiantes con bajo interés o desempeño a desarrollar interés en las carreras STEM.'), (4, 'Los docentes reciben desarrollo profesional sobre las diferencias culturales y de género para enriquecer la formación.'), (5, 'El aula STEM se diferencia en ubicar a todos los estudiantes, con una consideración especial hacia todos los grupos geográficos, socioeconómicos, raciales, étnicos y de género.'), (6, 'La institución está preparada para proveer una formación incluyente. Promueve las oportunidades de aprendizaje para todos los estudiantes, pero respeta las diferencias culturales y de género.')], max_length=1000, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='equidad',
            name='criterio',
            field=models.ManyToManyField(default='INFRAESTRUCTURA', to='DataBase.criterio'),
        ),
    ]
