# Generated by Django 4.2.5 on 2023-09-14 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0003_curriculoprogresivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionEstudiantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(help_text='Ingrese el nivel de prioridad del 1 al 10 para el numeral', null=True)),
                ('dep_responsable', models.CharField(default='Dirección', max_length=30)),
                ('track_year', models.IntegerField(help_text='Ingrese año de seguimiento')),
                ('track_date', models.CharField(help_text='Ingrese fecha de seguimiento', max_length=5)),
                ('internal_auditory_date', models.DateField(blank=True, default='31/01/2000', null=True)),
                ('internal_auditory_obs', models.TextField(blank=True, max_length=1000)),
                ('external_auditory_date', models.DateField(blank=True, default='31/01/2000', null=True)),
                ('external_auditory_obs', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numeral', models.CharField(choices=[('281', 'El currículo incluye actividades para que los docentes usen evaluaciones basadas en el desempeño para determinar el aprendizaje de los estudiantes.'), ('282', 'Las evaluaciones previas / posteriores se utilizan para mostrar el desarrollo académico de los estudiantes.'), ('283', 'Se diseñan las actividades para que los profesores observen y monitoreen el diálogo entre los estudiantes para evaluar los procesos en la resolución de problemas y la innovación.'), ('284', 'Se diseñan las actividades para que los estudiantes participen en la autoevaluación y el establecimiento de metas.'), ('285', 'La institución utiliza datos de evaluaciones estatales y escolares para impulsar las decisiones de la formación.'), ('286', 'Evaluación continua. Tipología de evaluación donde los alumnos son examinados continuamente.'), ('287', 'Asesoramiento personalizado. Tipología de evaluación enmarcada para demostrar si los alumnos han alcanzado objetivos educativos específicos, de acuerdo con su desarrollo personal.')], max_length=10000)),
                ('criterio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DataBase.criterio')),
                ('person_responsable', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DataBase.personresponsable')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CurriculoPropio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(help_text='Ingrese el nivel de prioridad del 1 al 10 para el numeral', null=True)),
                ('dep_responsable', models.CharField(default='Dirección', max_length=30)),
                ('track_year', models.IntegerField(help_text='Ingrese año de seguimiento')),
                ('track_date', models.CharField(help_text='Ingrese fecha de seguimiento', max_length=5)),
                ('internal_auditory_date', models.DateField(blank=True, default='31/01/2000', null=True)),
                ('internal_auditory_obs', models.TextField(blank=True, max_length=1000)),
                ('external_auditory_date', models.DateField(blank=True, default='31/01/2000', null=True)),
                ('external_auditory_obs', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numeral', models.CharField(choices=[('261', 'El currículo es desarrollado por docentes o personas especializadas de la institución educativa, esto incluye la creación de actividades y proyectos.'), ('262', 'El mejor aporte para un currículo en educación STEM será siempre aquel contenido creado por los propios profesores. Los profesores conocen sus estudiantes y saben qué temas y que aspectos les son interesantes y por eso pueden crear actividades y proyectos especiales para sus estudiantes.')], max_length=10000)),
                ('criterio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DataBase.criterio')),
                ('person_responsable', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DataBase.personresponsable')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
