# Generated by Django 4.2.5 on 2023-09-11 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0003_alter_aprendizajecentrado_internal_auditory_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompromisodelaCominudad',
            new_name='CompromisodelaComunidad',
        ),
    ]
