# Generated by Django 4.2.5 on 2023-09-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0004_alter_criterio_name_remove_equidad_criterio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterio',
            name='name',
            field=models.CharField(choices=[('1', 'INFRAESTRUCTURA'), ('2', 'CURRÍCULO'), ('3', 'FORMACIÓN / INSTRUCCIÓN / EVALUACIÓN'), ('4', 'PERSONAL DOCENTE Y ADMINISTRATIVO'), ('5', 'ESCUELA, COMUNIDAD Y PERTENENCIA')], default='INFRAESTRUCTURA', max_length=100, primary_key=True, serialize=False),
        ),
    ]
