# Generated by Django 4.2.5 on 2023-09-18 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0004_aprendizajeextendido_aprendizajeriguroso_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EducacionStemIntegrada',
        ),
    ]
