# Generated by Django 4.2.5 on 2023-09-18 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0004_convivenciaescolar_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compromisodelacomunidad',
            name='codigo',
            field=models.CharField(default='5.0.0.0', max_length=7),
        ),
        migrations.AlterField(
            model_name='convivenciaescolar',
            name='codigo',
            field=models.CharField(default='5.3.0.0', max_length=7),
        ),
        migrations.AlterField(
            model_name='relacionesconlacominudad',
            name='codigo',
            field=models.CharField(default='5.2.0.0', max_length=7),
        ),
        migrations.AlterField(
            model_name='sostenibilidadescuelacomunidadypertenencia',
            name='codigo',
            field=models.CharField(default='5.4.0.0', max_length=7),
        ),
        migrations.CreateModel(
            name='PlaneacionyCreaciondeActividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(help_text='Ingrese el nivel de prioridad del 1 al 10 para el numeral', null=True)),
                ('dep_responsable', models.CharField(default='Dirección', max_length=30)),
                ('track_year', models.IntegerField(help_text='Ingrese año de seguimiento')),
                ('track_date', models.CharField(help_text='Ingrese fecha de seguimiento', max_length=5)),
                ('internal_auditory_date', models.DateField(blank=True, default='31/01/2000', null=True)),
                ('internal_auditory_obs', models.TextField(blank=True, max_length=1000)),
                ('external_auditory_date', models.DateField(blank=True, default='31/01/2000', null=True)),
                ('external_auditory_obs', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numeral', models.CharField(choices=[('Planeación y creación de actividades', '3300'), ('Las actividades planeadas y diseñadas incluyen métodos de indagación e investigación.', '3310'), ('Las actividades planeadas incluyen modelos explicativos y pensamiento crítico.', '3320'), ('Los estudiantes participarán en actividades que incluyen problemas auténticos del mundo real', '3330'), ('Los estudiantes deben enfrentar problemas del mundo real, globales, de su país, región o ciudad, problemas que le son de su diario vivir.', '3331'), ('La educación STEM pone en contexto problemas de la vida que un ciudadano preparado debe poder enfrentar o que al menos participe en discusiones públicas donde aporte soluciones a la comunidad.', '3332'), ('Los profesores se reúnen regularmente para reflexionar sobre el trabajo de los estudiantes.', '3340'), ('La institución mantiene docentes que capacitan otros docentes en el ámbito de lo formativo y pedagógico', '3350')], max_length=10000)),
                ('codigo', models.CharField(default='3300', max_length=7)),
                ('criterio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DataBase.criterio')),
                ('person_responsable', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DataBase.personresponsable')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EstrategiasFormativas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(help_text='Ingrese el nivel de prioridad del 1 al 10 para el numeral', null=True)),
                ('dep_responsable', models.CharField(default='Dirección', max_length=30)),
                ('track_year', models.IntegerField(help_text='Ingrese año de seguimiento')),
                ('track_date', models.CharField(help_text='Ingrese fecha de seguimiento', max_length=5)),
                ('internal_auditory_date', models.DateField(blank=True, default='31/01/2000', null=True)),
                ('internal_auditory_obs', models.TextField(blank=True, max_length=1000)),
                ('external_auditory_date', models.DateField(blank=True, default='31/01/2000', null=True)),
                ('external_auditory_obs', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numeral', models.CharField(choices=[('Estrategias formativas', '3600'), ('Los estudiantes utilizan el proceso de diseño en ingeniería en la mayor parte de las actividades escolares y por lo tanto sus procesos formativos se dan siempre en equipo. Todo esto en la búsqueda de la solución de problemas (en ingeniería) y de respuestas (en ciencias).', '3610'), ('El docente sirve como facilitador a través de preguntas, las escucha y hace de guía de los estudiantes en el camino de su aprendizaje.', '3620'), ('Los profesores diseñan actividades basándose en las necesidades de los proyectos de los estudiantes.', '3630'), ('La instrucción apoya el discurso de los estudiantes a través de la redacción de informes y presentaciones orales, todos alineados con los estándares de su formación.', '3640')], max_length=10000)),
                ('codigo', models.CharField(default='3600', max_length=7)),
                ('criterio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DataBase.criterio')),
                ('person_responsable', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DataBase.personresponsable')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AprendizajeRiguroso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(help_text='Ingrese el nivel de prioridad del 1 al 10 para el numeral', null=True)),
                ('dep_responsable', models.CharField(default='Dirección', max_length=30)),
                ('track_year', models.IntegerField(help_text='Ingrese año de seguimiento')),
                ('track_date', models.CharField(help_text='Ingrese fecha de seguimiento', max_length=5)),
                ('internal_auditory_date', models.DateField(blank=True, default='31/01/2000', null=True)),
                ('internal_auditory_obs', models.TextField(blank=True, max_length=1000)),
                ('external_auditory_date', models.DateField(blank=True, default='31/01/2000', null=True)),
                ('external_auditory_obs', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numeral', models.CharField(choices=[('Aprendizaje Riguroso', '3200'), ('Los estudiantes deben enfrentar problemas del mundo real, globales, de su país, región o ciudad, problemas que le son de su diario vivir.', '3210'), ('Trabajo cognitivo exigente. Los estudiantes utilizan hábitos mentales, llegan a conclusiones basadas en la evidencia, predicen fenómenos y comportamientos, analizan datos, explican y razonan.', '3220'), ('Conclusiones basadas en la evidencia', '3221'), ('El estudiante predice fenómenos y comportamientos', '3222'), ('El estudiante analiza datos', '3223'), ('El estudiante explica y razona', '3224'), ('Los estudiantes se involucran en auténticas actividades colaborativas basadas en la investigación', '3225'), ('Las prácticas de matemáticas se presentan de forma transversal en las actividades de la gran mayoría de las asignaturas', '3230'), ('Encontrar sentido a los problemas y perseverar en resolverlos', '3231'), ('Modelar con matemáticas', '3232'), ('Utilizar estratégicamente herramientas apropiadas', '3233'), ('Esmerarse por ser preciso', '3234'), ('Razonar de manera abstracta y cuantitativamente', '3235'), ('Buscar y hacer uso de estructuras', '3236'), ('Construir posibles argumentos y criticar el razonamiento de otros', '3237'), ('Buscar patrones de cálculo y aplicar métodos generales o autónomos', '3238'), ('Desarrollo en la institución de una cultura de aprendizaje continuo y durante toda la vida. Desarrollo del estudiante como un consumidor crítico, coherente e informado.', '3240')], max_length=10000)),
                ('codigo', models.CharField(default='3200', max_length=7)),
                ('criterio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DataBase.criterio')),
                ('person_responsable', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DataBase.personresponsable')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AprendizajeExtendido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(help_text='Ingrese el nivel de prioridad del 1 al 10 para el numeral', null=True)),
                ('dep_responsable', models.CharField(default='Dirección', max_length=30)),
                ('track_year', models.IntegerField(help_text='Ingrese año de seguimiento')),
                ('track_date', models.CharField(help_text='Ingrese fecha de seguimiento', max_length=5)),
                ('internal_auditory_date', models.DateField(blank=True, default='31/01/2000', null=True)),
                ('internal_auditory_obs', models.TextField(blank=True, max_length=1000)),
                ('external_auditory_date', models.DateField(blank=True, default='31/01/2000', null=True)),
                ('external_auditory_obs', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numeral', models.CharField(choices=[('Aprendizaje extendido', '3800'), ('Las experiencias STEM están directamente conectadas con el aprendizaje en clase.', '3810'), ('El aprendizaje extendido incluye experiencias de campo y aprendizaje auténtico y contextual.', '3823'), ('Existen oportunidades para que los estudiantes mayores participen en pasantías después de la jornada de estudio o los fines de semana.', '3830'), ('El programa está asociado a algún parque de ciencia o museo', '3840'), ('El aprendizaje extendido está alineado con los estándares básicos de competencias en lenguaje, matemáticas, ciencias y competencias ciudadanas.', '3850'), ('Se utilizan guías para programas de formación extracurricular', '3860'), ('El programa extracurricular realiza sus propias evaluaciones y observaciones para garantizar la calidad de la experiencia STEM', '3870'), ('El programa extracurricular utiliza herramientas de observación basadas en la investigación alineadas con los estándares de experiencia STEM.', '3880'), ('Los estudiantes tienen experiencias directas con profesionales de STEM en entornos auténticos fuera del día escolar', '3890'), ('El trabajo de los alumnos se exhibe y se muestra a la comunidad y en el sitio web de la institución.', '38100'), ('Los estudiantes deben poder tener la oportunidad de involucrarse en actividades adicionales de todo tipo, culturales, deportes, artísticas y también en actividades en educación STEM que los exponga a otros contextos para que puedan tener una perspectiva más amplia de la vida y de las oportunidades que se ofrecen. De esta forma tendremos más oportunidades para un aprendizaje holístico.', '38110')], max_length=10000)),
                ('codigo', models.CharField(default='5.2.0.0', max_length=7)),
                ('criterio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DataBase.criterio')),
                ('person_responsable', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DataBase.personresponsable')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
