# Generated by Django 4.2.5 on 2023-09-09 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0004_merge_20230909_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inclusion_ingenieria_aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeral', models.CharField(choices=[('221', 'Inclusión del proceso de diseño en ingeniería en el currículo.'), ('222', 'Los docentes de la mayoría de las asignaturas adoptan el proceso de diseño como parte fundamental del desarrollo pedagógico.'), ('223', 'El proceso de diseño se ejecuta de forma intencional dado el potencial pedagógico de cada una de sus fases.'), ('224', 'Las actividades se diseñan con el objetivo de incluir el pensamiento computacional y el pensamiento matemático en la gran mayoría de las asignaturas.'), ('225', 'Actividades de prototipado en espacios para la creatividad (Maker Spaces)')], max_length=1000)),
                ('priority_model', models.CharField(choices=[('Exploratorio', 'Exploratorio'), ('Introductorio', 'Introductorio'), ('Inmersión parcial', 'Inmersión parcial'), ('Inmersión completa', 'Inmersión completa')], default='Introductorio', max_length=20)),
                ('dep_responsable', models.CharField(default='Dirección', max_length=30)),
                ('track_year', models.IntegerField(help_text='Ingrese año de seguimiento')),
                ('track_date', models.CharField(help_text='Ingrese fecha de seguimiento', max_length=5)),
                ('internal_auditory_date', models.DateField(default='2000-01-31', null=True)),
                ('internal_auditory_obs', models.TextField(blank=True, max_length=1000)),
                ('external_auditory_date', models.DateField(blank=True, default='2000-01-31', null=True)),
                ('external_auditory_obs', models.TextField(blank=True, max_length=1000)),
                ('criterio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DataBase.criterio')),
                ('person_responsable', models.ManyToManyField(help_text='Seleccione un responsable', to='DataBase.personresponsable')),
            ],
        ),
    ]
