# Generated by Django 4.2.5 on 2023-09-05 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0005_alter_criterio_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equidad',
            name='criterio',
        ),
        migrations.AddField(
            model_name='equidad',
            name='criterio',
            field=models.ForeignKey(default='INFRAESTRUCTURA', null=True, on_delete=django.db.models.deletion.SET_NULL, to='DataBase.criterio'),
        ),
    ]
