# Generated by Django 4.2.5 on 2023-09-10 02:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0005_inclusion_ingenieria_aula'),
    ]

    operations = [
        migrations.AddField(
            model_name='inclusion_ingenieria_aula',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
