# Generated by Django 4.2.5 on 2023-09-05 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0006_remove_equidad_criterio_equidad_criterio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterio',
            name='name',
            field=models.CharField(choices=[('INFRAESTRUCTURA', 'INFRAESTRUCTURA'), ('CURRÍCULO', 'CURRÍCULO'), ('FORMACIÓN / INSTRUCCIÓN / EVALUACIÓN', 'FORMACIÓN / INSTRUCCIÓN / EVALUACIÓN'), ('PERSONAL DOCENTE Y ADMINISTRATIVO', 'PERSONAL DOCENTE Y ADMINISTRATIVO'), ('ESCUELA, COMUNIDAD Y PERTENENCIA', 'ESCUELA, COMUNIDAD Y PERTENENCIA')], default='INFRAESTRUCTURA', max_length=100, primary_key=True, serialize=False),
        ),
    ]
