# Generated by Django 4.2.5 on 2023-09-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0006_inclusion_ingenieria_aula_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='inclusion_ingenieria_aula',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='inclusion_ingenieria_aula',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='inclusion_ingenieria_aula',
            name='external_auditory_date',
            field=models.DateField(blank=True, default='31/01/2000', null=True),
        ),
        migrations.AlterField(
            model_name='inclusion_ingenieria_aula',
            name='internal_auditory_date',
            field=models.DateField(blank=True, default='31/01/2000', null=True),
        ),
        migrations.AlterField(
            model_name='inclusion_ingenieria_aula',
            name='person_responsable',
            field=models.ManyToManyField(default=None, help_text='Seleccione un responsable', to='DataBase.personresponsable'),
        ),
        migrations.AlterField(
            model_name='inclusion_ingenieria_aula',
            name='priority_model',
            field=models.CharField(choices=[(' ', 'Exploratorio'), (' ', 'Introductorio'), ('', 'Inmerción parcial'), (' ', 'Inmerción completa')], default='Introductorio', max_length=4),
        ),
    ]
