# Generated by Django 4.2.5 on 2023-09-10 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0007_inclusion_ingenieria_aula_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desarrollo_ciudadania_digital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_model', models.CharField(choices=[(' ', 'Exploratorio'), (' ', 'Introductorio'), ('', 'Inmerción parcial'), (' ', 'Inmerción completa')], default='Introductorio', max_length=4)),
                ('dep_responsable', models.CharField(default='Dirección', max_length=30)),
                ('track_year', models.IntegerField(help_text='Ingrese año de seguimiento')),
                ('track_date', models.CharField(help_text='Ingrese fecha de seguimiento', max_length=5)),
                ('internal_auditory_date', models.DateField(blank=True, default='31/01/2000', null=True)),
                ('internal_auditory_obs', models.TextField(blank=True, max_length=1000)),
                ('external_auditory_date', models.DateField(blank=True, default='31/01/2000', null=True)),
                ('external_auditory_obs', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numeral', models.CharField(choices=[('231', 'Establecimiento de una alfabetización digital como parte del entendimiento y el alcance de los desarrollos dentro de la 4a revolución industrial.'), ('232', 'Integración del mundo real al mundo virtual y su relación con la vida personal y laboral.'), ('233', 'Integración constante de nuevos desarrollos digitales dentro de actividades curriculares.'), ('234', 'Desarrollo de hábitos de aprendizaje continuo sobre nuevas alternativas y soluciones que aparecen dentro del mundo digital con miras al conocimiento crítico como consumidor y productor digital.')], max_length=1000)),
                ('criterio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DataBase.criterio')),
                ('person_responsable', models.ManyToManyField(default=None, help_text='Seleccione un responsable', to='DataBase.personresponsable')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
