# Generated by Django 4.2.5 on 2023-09-05 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0008_alter_equidad_item_alter_equidad_priority_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterio',
            name='name',
            field=models.CharField(choices=[('INFRAESTRUCTURA', ' '), ('CURRÍCULO', ' '), ('FORMACIÓN / INSTRUCCIÓN / EVALUACIÓN', ' '), ('PERSONAL DOCENTE Y ADMINISTRATIVO', ' '), ('ESCUELA, COMUNIDAD Y PERTENENCIA', ' ')], default='INFRAESTRUCTURA', max_length=100, primary_key=True, serialize=False),
        ),
    ]
