# Generated by Django 4.2.5 on 2023-09-11 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0008_desarrollo_ciudadania_digital'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equidad',
        ),
    ]
