# Generated by Django 4.2.5 on 2023-09-06 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0009_alter_criterio_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equidad',
            old_name='item',
            new_name='numeral',
        ),
    ]
