# Generated by Django 4.2.5 on 2023-09-13 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0004_rename_compromisodelacominudad_compromisodelacomunidad'),
        ('DataBase', '0009_delete_equidad'),
    ]

    operations = [
    ]
