# Generated by Django 4.2.5 on 2023-09-13 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0010_merge_20230913_1747'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sostenibilidad_EscuelaComunidadyPertenencia',
            new_name='SostenibilidadEscuelaComunidadyPertenencia',
        ),
    ]
