# Generated by Django 4.2.5 on 2023-09-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0011_alter_equidad_numeral'),
    ]

    operations = [
        migrations.AddField(
            model_name='equidad',
            name='sub_numeral',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='personresponsable',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=200),
        ),
        migrations.AddField(
            model_name='personresponsable',
            name='first_name',
            field=models.CharField(help_text='name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personresponsable',
            name='last_name',
            field=models.CharField(default='', help_text='last name', max_length=100),
        ),
        migrations.AddField(
            model_name='personresponsable',
            name='phone_number',
            field=models.CharField(help_text='Numero de telefono', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='personresponsable',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
