# Generated by Django 4.2.5 on 2023-09-13 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0011_rename_sostenibilidad_escuelacomunidadypertenencia_sostenibilidadescuelacomunidadypertenencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='compromisodelacomunidad',
            name='texto',
            field=models.TextField(blank=True, editable=False, max_length=10000, verbose_name='Texto del Item'),
        ),
        migrations.AlterField(
            model_name='compromisodelacomunidad',
            name='numeral',
            field=models.CharField(choices=[('511', 'Los miembros de la comunidad son socios en el liderazgo del Programa en Educación STEM, evaluación de necesidades y guía de ayuda para la institución.'), ('512', 'El programa ha incluido a diversos socios para guiar el trabajo en la institución.'), ('513', 'Existen oportunidades para presentar el trabajo de los estudiantes a través de eventos comunitarios a través de exposiciones en el sitio o en línea.'), ('514', 'La institución recopila y utiliza los comentarios de los padres / la comunidad para evaluar el progreso de la implementación del Programa en Educación STEM.'), ('515', 'La escuela proporciona oportunidades de sensibilización comunitaria para los padres. Hay comunicación permanente a los padres de familia.')], max_length=3, verbose_name='Numeral'),
        ),
    ]
