# Generated by Django 4.2.5 on 2023-09-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0011_register_equidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.CharField(help_text='Ingrese el teléfono de la institución', max_length=15),
        ),
    ]
