# Generated by Django 4.2.5 on 2023-09-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0012_equidad_sub_numeral_personresponsable_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personresponsable',
            name='id',
        ),
        migrations.AddField(
            model_name='auditory',
            name='external_audit_observations',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AddField(
            model_name='auditory',
            name='internal_audit_date',
            field=models.CharField(default=' ', max_length=30),
        ),
        migrations.AddField(
            model_name='auditory',
            name='internal_audit_observations',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AlterField(
            model_name='criterio',
            name='name',
            field=models.CharField(choices=[('INFRAESTRUCTURA', 'INFRAESTRUCTURA'), ('CURRÍCULO', 'CURRÍCULO'), ('FORMACIÓN / INSTRUCCIÓN / EVALUACIÓN', 'FORMACIÓN / INSTRUCCIÓN / EVALUACIÓN'), ('PERSONAL DOCENTE Y ADMINISTRATIVO', 'PERSONAL DOCENTE Y ADMINISTRATIVO'), ('ESCUELA, COMUNIDAD Y PERTENENCIA', 'ESCUELA, COMUNIDAD Y PERTENENCIA')], default='', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='personresponsable',
            name='last_name',
            field=models.CharField(default='', help_text='last name', max_length=100, primary_key=True, serialize=False),
        ),
    ]
