# Generated by Django 4.2.5 on 2023-09-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0013_remove_personresponsable_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditory',
            name='external_audit_date',
            field=models.CharField(default=' ', max_length=30),
        ),
    ]
