# Generated by Django 4.2.5 on 2023-09-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0014_auditory_external_audit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditory',
            name='internal_audit_date',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
