# Generated by Django 4.2.5 on 2023-09-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0015_alter_auditory_internal_audit_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditory',
            old_name='internal_audit_observations',
            new_name='InternalAuditObservations',
        ),
        migrations.RemoveField(
            model_name='auditory',
            name='id',
        ),
        migrations.RemoveField(
            model_name='auditory',
            name='internal_audit_date',
        ),
        migrations.AddField(
            model_name='auditory',
            name='InternalAuditDate',
            field=models.CharField(default=' ', max_length=30, primary_key=True, serialize=False),
        ),
    ]
