# Generated by Django 4.2.5 on 2023-09-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0016_rename_internal_audit_observations_auditory_internalauditobservations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personresponsable',
            name='last_name',
            field=models.CharField(help_text='last name', max_length=100, primary_key=True, serialize=False),
        ),
    ]
