# Generated by Django 4.2.5 on 2023-09-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0018_alter_personresponsable_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditory',
            name='InternalAuditDate',
        ),
        migrations.RemoveField(
            model_name='auditory',
            name='InternalAuditObservations',
        ),
        migrations.RemoveField(
            model_name='auditory',
            name='external_audit_date',
        ),
        migrations.RemoveField(
            model_name='auditory',
            name='external_audit_observations',
        ),
        migrations.AddField(
            model_name='auditory',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
