# Generated by Django 4.2.5 on 2023-09-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0019_remove_auditory_internalauditdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personresponsable',
            name='last_name',
            field=models.CharField(default='n/a', max_length=100, primary_key=True, serialize=False),
        ),
    ]
