# Generated by Django 4.2.5 on 2023-09-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0020_alter_personresponsable_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personresponsable',
            name='last_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
