# Generated by Django 4.2.5 on 2023-09-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0022_alter_personresponsable_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditory',
            name='InternalAuditDate',
            field=models.CharField(default=' ', max_length=30),
        ),
        migrations.AddField(
            model_name='auditory',
            name='InternalAuditObservations',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AddField(
            model_name='auditory',
            name='external_audit_date',
            field=models.CharField(default=' ', max_length=30),
        ),
        migrations.AddField(
            model_name='auditory',
            name='external_audit_observations',
            field=models.CharField(default=' ', max_length=500),
        ),
    ]
